version: "3"
services:
  web:
    image: "node:latest"
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && npm start"
    working_dir: "/usr/src/app"
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
      # Don't sync the node_modules directory back to the client.
      - "/usr/src/app/node_modules"
    depends_on:
      - pg
  pg:
    image: postgres:9.3
    restart: always
    ports:
      - 8888:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: devdb
volumes:
  postgres-data: