version: "3"
services:
  toolwall-landing:
    image: node:latest
    entrypoint:
      - "sh"
      - "-c"
      - "yarn install && yarn dev"
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
    volumes:
      - ".:/usr/src/app"
      # Don't sync the node_modules directory back to the client.
      - "/usr/src/app/node_modules"
