source 'https://rubygems.org'

gem 'rack-contrib'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-param', require: 'sinatra/param'
gem 'sorbet-runtime'

group :development do
  gem 'pry'
  gem 'pry-byebug'
  gem 'awesome_print'
  gem 'solargraph'
end

group :test do
  gem 'rspec'
  gem 'vcr'
end
